events {}

http {
    upstream backend_servers {
        server web_server_1:80 max_fails=1 fail_timeout=5s;
        server web_server_2:80 max_fails=1 fail_timeout=5s;
    }

    server {
        listen 8087; # Berjalan di port 8087 lokal

        location / {
            proxy_pass http://backend_servers;
            
            # Layer 7 dapat memanipulasi HTTP Header aplikasi
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Menambahkan header kustom untuk bukti ini dikerjakan di Layer 7
            add_header X-LoadBalancer-Type "Layer-7-Application-Aware";
        }
    }
}